language: scala

sudo: true

git:
  depth: 1

scala:
  - "2.12.4"

jdk:
  - oraclejdk8

services:
  - docker

before_install:
  - sudo apt-get install wget curl

script:
  - sh ./scripts/build.sh all
  - sh ./scripts/upload.sh

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
